### PR TITLE
Bump minor release

### PR DESCRIPTION
**Pull request by rofinn**
There have been 14 commits with some significant changes since the last release.

### CODE REVIEW

**Comment by wildart** [comment]
Can you setup this packages with Registrator & TagBot?

**Comment by rofinn** [comment]
I don't think I have permission to change the settings on this repo.

**Comment by nalimilan** [comment]
They are both enabled AFAICT.

**Comment by wildart** [comment]
@JuliaRegistrator register()

**Comment by kescobo** [comment]
Thanks!

**Pull request merged**
