### PR TITLE
Documenter-based docs

### PR DESCRIPTION
**Pull request by wildart**
Added build script and index page for Documenter-based docs

### CODE REVIEW

**Comment by wildart** [comment]
@ararslan Could you setup GH pages for this repo to point to `gh-pages` branch, so we'll get new docs available?

**Comment by ararslan** [comment]
Done

**Comment by wildart** [comment]
Something is not right. I cannot access docs at https://juliastats.org/MultivariateStats.jl/dev/. Is that because of `juliastats.org` custom domain?

**Comment by ararslan** [comment]
I think we'll need to rerun a Documenter build, or so I assume.

**Comment by wildart** [comment]
I got [new commit](https://github.com/JuliaStats/MultivariateStats.jl/commits/gh-pages) in `gh-pages` branch after [Documenter action rerun](https://github.com/JuliaStats/MultivariateStats.jl/runs/2104366700?check_suite_focus=true) but it's still not visible.

**Comment by ararslan** [comment]
Ah, the repo was missing the requisite keys. I've added them. Can you retry building however it is you did so?

**Comment by wildart** [comment]
Nope, it didn't work. See here https://github.com/JuliaStats/MultivariateStats.jl/commits/gh-pages.

For some reason error message relates to `/docs` branch. See https://github.com/JuliaStats/MultivariateStats.jl/runs/2134225085. We need a root of `gh-pages`.

**Comment by ararslan** [comment]
Ah, that was my bad. I've fixed it and it looks like we now have docs: http://juliastats.org/MultivariateStats.jl/dev/

**Comment by wildart** [comment]
:+1:

**Pull request merged**
